complete -c toli -l how -d 'Get help on how to perform a task'
complete -c toli -l do -d 'Execute a task based on natural language description'
complete -c toli -l explain -d 'Explain what a given command does'
complete -c toli -l alias -d 'Suggest aliases for a given command'
complete -c toli -l version -d 'Show version information'